# Generated by Django 4.0.3 on 2022-03-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospítalGeneral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroFactura', models.CharField(max_length=15)),
                ('empresa', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('monto', models.CharField(max_length=15)),
            ],
        ),
    ]
